sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -f Dockerfile.arm -t kurai/jankenpon-game-instance-go-arm .

# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push kurai/jankenpon-game-instance-go-arm
  fi
